const firstName = 'Hello World';
console.log(firstName);
const greeting = "Bonjour je m'appelle";
let prenom = 'Lionel';
console.log(greeting + ' ' + prenom);
const me = "j'ai";
console.log(me);
let firstNumber = 2;
let secondNumber = 0;
console.log(me + ' ' + firstNumber + secondNumber);
const age = 'ans';
console.log(age);
console.log(me + ' ' + firstNumber + secondNumber + ans);
